# Generated by Django 4.2.16 on 2024-10-27 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HookahTobacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hookahTobacco_images/')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('blond', 'Rubio'), ('dark', 'Negro')], max_length=20)),
                ('description', models.TextField()),
                ('averageRating', models.FloatField(default=0)),
                ('ratingCount', models.PositiveIntegerField(default=0)),
                ('registeredDay', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
